### PR TITLE
Add support for initial effects cleanup

### PR DESCRIPTION
**Pull request by janovekj**
This PR aims to enable cleanup for effects that are executed as part of the state initialization.

Was there a particular reason this was not possible in the first place?

Please note that 32cff1d needs some attention before it can be merged. I had to `@ts-ignore` an error that should probably not have to be ignored. It seems this error is disappears in later TS versions (>3.8), but I'm not sure when/why. At least, all was good when I was using TS 4.0.3, which was the globally installed version on my machine. Have not tested with other versions. The error would also disappear if I just added some extra type narrowing by doing 
```ts
fetchData(_, effect) {
  setTimeout(() => {
    if (effect.type === "fetchData") {
     dispatch({ type: 'RESOLVE', data: effect.data.toUpperCase() });
    }
  }, 20);
}
```
but it seems like that shouldn't be necessary. Is this a known issue?

### CODE REVIEW

**Comment by davidkpiano** [comment]
Thanks! Are you using the latest version of TypeScript? I don't get any TS errors locally with this.

**Comment by davidkpiano** [comment]
Thanks! I don't get any type errors with TypeScript v.4.1.x (which is the latest version on VS Code).

**Comment by janovekj** [comment]
Sorry, I should have added that the error only appears when running the tests. Everything works fine in VS Code itself, but I guess the tests run with TS 3.8.3, since that's what's installed for the project in `package.json`.

I think this is the first test where a union type is passed into the `TEffect` param of `EffectReducer`, which would explain why this error haven't surfaced before. 

[This change from TS 3.9](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#intersections-reduced-by-discriminant-properties) might be related to fixing this error, so maybe a good option would be to update the project's TS version.

Let me know what you think, and I'll make the needed changes :)

**Comment by davidkpiano** [comment]
I think upgrading TS would be a good idea, if you want to do this in this PR as well.

Thank you!

**Comment by janovekj** [comment]
Great! 

I upgraded to the latest version, but TSDX ships with a version of `@typescript-eslint` that doesn't support the newer TS versions, I had to add a couple of manual resolutions for those packages, otherwise I would get errors during linting ([relevant-ish SO post](https://stackoverflow.com/questions/62079477/line-0-parsing-error-cannot-read-property-map-of-undefined)). Hope that's OK!

**Comment by davidkpiano** [comment]
Thanks for doing that! I've been seeing the same ESLint issues in other TSDX projects, so I'm glad to know there's a workaround.

This LGTM!

**Comment by janovekj** [comment]
Awesome! Thanks for the quick responses, and for making this library in the first place - I'm having a great time with it.

**Comment by janovekj** [comment]
Would it be possible to have this released in the near future? Feel free to let me know if there's anything I can do to help.

**Pull request merged**
